### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by emersonlaurentino** [octachrome/treason#54]
Hi, I want to make my own version of Coup and before that, I came to look if there was already something open source. I found your repository and I'm curious if you care about copyright, as this is my main fear.

**Comment by octachrome** [comment]
I guess your question is about whether I am concerned about infringing the copyright held by the original game designer.

First off, the consensus is that game mechanics cannot be copyrighted: you can only copyright graphics (I only use open source icons, and none of the official art) and text (I rewrote the game rules etc in my own words). I use key words like "duke", but you can't copyright a single word. Google the subject to find out more.

Secondly, early on in development I emailed Rikki Tahta, the designer of Coup, to ask him about creating an online version, and he told me he had licensed the game to Banana & Co for a mobile, and said "I don't know if allowing you a license officially contravenes anything but go ahead so long as it's for fun and they don't complain." I didn't contact Banana & Co app, but I assume they would not mind because their business is mobile games, and Treason Coup is a website. Also I do not make any money from the game. If I did make money from it, that might be a different question.

**Comment by emersonlaurentino** [comment]
Ah, very good!! Thank you for clarifying my doubts. I have one last question: could you explain to me what would be the difference between game rules and game mechanics when referring to Coup?

**Comment by octachrome** [comment]
When I say game mechanics I mean the rules really: the cards/pieces, what you do on your turn, etc. I said "mechanics" to be clear that I didn't mean the exact words in the rule booklet, which is copyrighted.

**Comment by emersonlaurentino** [comment]
Thanks @octachrome!
